app_group:
  - read:
      path: /apps/bootstrap.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}/_targets
      method: GET
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}/_topology
      method: POST
  - create:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}/_topology
      method: POST

resource_history:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}/_revs
      method: GET
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}/_topology
      method: GET
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}
      method: DELETE
  - delete:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.bootstrap.v1alpha1.init:
  - create:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits
      method: POST
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}
      method: GET
  - update:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}
      method: PUT
  - update:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/{name}
      method: PATCH

com.nokia.eda.bootstrap.v1alpha1.init_list:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/inits
      method: GET
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits
      method: GET
  - delete:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits
      method: DELETE

com.nokia.eda.bootstrap.v1alpha1.init_deleted_resources:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/inits/_deleted
      method: GET

com.nokia.eda.bootstrap.v1alpha1.management_router:
  - create:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters
      method: POST
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}
      method: GET
  - update:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}
      method: PUT
  - update:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/{name}
      method: PATCH

com.nokia.eda.bootstrap.v1alpha1.management_router_list:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/managementrouters
      method: GET
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters
      method: GET
  - delete:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters
      method: DELETE

com.nokia.eda.bootstrap.v1alpha1.management_router_deleted_resources:
  - read:
      path: /apps/bootstrap.eda.nokia.com/v1alpha1/namespaces/{namespace}/managementrouters/_deleted
      method: GET

totalPaths: 17
totalSchemas: 61
usedSchemas: 14
unusedSchemas: 47
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Patch
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.bootstrap.v1alpha1.Init_DeletedResourceEntry
  - com.nokia.eda.bootstrap.v1alpha1.Init_alarms
  - com.nokia.eda.bootstrap.v1alpha1.Init_deviations
  - com.nokia.eda.bootstrap.v1alpha1.Init_metadata
  - com.nokia.eda.bootstrap.v1alpha1.ManagementRouter_DeletedResourceEntry
  - com.nokia.eda.bootstrap.v1alpha1.ManagementRouter_alarms
  - com.nokia.eda.bootstrap.v1alpha1.ManagementRouter_deviations
  - com.nokia.eda.bootstrap.v1alpha1.ManagementRouter_metadata
